 platform :ios, '9.0'

target 'CurrenC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrenC

pod 'Alamofire'
pod 'SwiftyJSON'

end
